<?php
/**
 * Copyright (C) 2015 Esendex Ltd.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the Esendex Community License v1.0 as published by
 * the Esendex Ltd.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * Esendex Community Licence v1.0 for more details.
 *
 * You should have received a copy of the Esendex Community Licence v1.0
 * along with this program.  If not, see <http://www.esendex.com/esendexcommunitylicence/>
 */

$helper = Mage::helper('esendex_sms');
?>

<div style="text-align: right;">
    <a href="https://www.esendex.com/redirect?i=sentmessages&ls=magento&sc=connectstore&sd=v1" title="<?= $helper->__('Download all messages') ?>">
        <?= $helper->__('Download all messages') ?>
    </a>
</div>
